/**
 * AiRead — the AI summary surface, shared by Thematic View and L2.
 * Borderless card with a left-edge indigo→purple accent (the one AI gradient);
 * named header with the spark badge; optional footer slot for a CTA.
 */
import { Spark } from './Shell'

export function AiRead({
  verdict,
  body,
  ask,
  meta,
  footer,
  overlap,
  title = 'AI Summary',
}: {
  verdict: React.ReactNode
  body: React.ReactNode
  ask?: React.ReactNode
  meta?: React.ReactNode
  footer?: React.ReactNode
  overlap?: boolean
  title?: string
}) {
  return (
    <section className={`ai-frame shadow-(--shadow-card) ${overlap ? '-mt-8' : ''}`} aria-label={title}>
      <div className="ai-glass p-6">
        <div className="mb-3 flex items-baseline justify-between gap-4">
          <span className="flex items-center gap-2">
            <span className="relative flex h-6 w-6 items-center justify-center">
              <span
                aria-hidden
                className="spark-glow absolute inset-0 rounded-full"
                style={{ background: 'var(--ai-border-gradient)', filter: 'blur(5px)' }}
              />
              <span
                className="relative flex h-6 w-6 items-center justify-center rounded-chip"
                style={{ background: 'var(--ai-wash-subtle)' }}
              >
                <span className="spark-anim flex">
                  <Spark size={13} />
                </span>
              </span>
            </span>
            <span className="label" style={{ color: 'var(--ai-green-mid)' }}>
              {title}
            </span>
          </span>
          <span className="text-[11px] text-ink-mute max-sm:hidden">Generated by BOTaina from Q1 2026 cells</span>
        </div>

        <p className="voice text-[19px] leading-snug text-ink">{verdict}</p>
        <div className="mt-3 text-[13.5px] leading-relaxed text-ink-soft">{body}</div>
        {ask && <p className="voice mt-2.5 text-[13.5px] italic text-sidra">{ask}</p>}
        {meta && <p className="mt-2.5 text-[11.5px] text-ink-mute">{meta}</p>}
        {footer && <div className="mt-4">{footer}</div>}
      </div>
    </section>
  )
}
